pub mod annotate;
pub mod component_scope_check;
pub mod consistency_check;
pub mod control_css_check;
pub mod control_structure_check;
pub mod css_resolve;
pub mod css_rules;
pub mod diagnostic;
pub mod fence_gate;
pub mod inline_context_check;
pub mod ir;
pub mod layout_transition_check;
pub mod paint_order_check;
pub mod pipeline;
pub mod projected_check;
pub mod rich_text_classify;
pub mod schema;
pub mod structural;
pub mod tree_builder;
pub mod value_check;

pub use diagnostic::Diagnostic;
pub use ir::{IrElement, IrNode, IrNodeKind, IrTree};
pub use pipeline::{parse_template, parse_template_with_css, ParsedTemplate};
pub use schema::{Category, ContentModel, SemanticKind, TagSpec};
