#!/usr/bin/env python3
"""Generate preview/components-registry.js for manual file:// preview.

Reads showcase/showcase/components/*.html and emits a JS registry
(window.__LOOM_COMPONENTS__, same format rect-diff's browser-rect.mjs
injects) so double-clicking a page HTML expands Custom Elements in the
browser too. The generated file never overwrites an injected registry.

Re-run after adding/changing components/, then commit the result.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMP_DIR = ROOT / "showcase" / "components"
OUT = ROOT / "showcase" / "preview" / "components-registry.js"


def main() -> int:
    registry = {}
    for f in sorted(COMP_DIR.glob("*.html")):
        registry[f.stem] = f.read_text(encoding="utf-8")
    entries = ",\n".join(
        f"  {json.dumps(name)}: {json.dumps(src)}"
        for name, src in registry.items()
    )
    OUT.write_text(
        "// Auto-generated by showcase/scripts/gen-preview-registry.py — do not edit.\n"
        "// Component registry for manual file:// preview (same format rect-diff\n"
        "// injects via browser-rect.mjs). Only set if not already injected.\n"
        "window.__LOOM_COMPONENTS__ = window.__LOOM_COMPONENTS__ || {\n"
        f"{entries}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(registry)} components: {', '.join(registry)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
