// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace LoomGUI.Bindings
{
    internal static unsafe partial class Native
    {
        const string __DllName = "loomgui_ffi_c";





        /// <summary>
        ///  版本字符串（C null-terminated `b"v1e\0"`）。
        ///
        ///  返回 `*const u8`（csbindgen 映射为 C# `byte*`）；CString::as_ptr 给的是
        ///  `*const c_char`（i8），这里 cast 对齐签名。OnceLock 缓存，避免每次分配+泄漏。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* loomgui_version();

        /// <summary>
        ///  创建 Stage 句柄。`font_path` 为 UTF-8 字节（指针+len），失败返回 null。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern StageHandle* loomgui_stage_new(byte* font_path, nuint fp_len, float w, float h);

        /// <summary>
        ///  null-safe 释放 Stage 句柄。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_free(StageHandle* h);

        /// <summary>
        ///  装载 HTML+CSS 文本（指针+len）。0=ok，-1=err。null/非 UTF-8 返回 -1。
        ///
        ///  **parse-gated：**本函数走核心 HTML/CSS 解析路径，`--no-default-features` 关掉 parse 时不存在。
        ///  包加载路径走 `loomgui_stage_load_package`（常驻，不 gate）。
        ///
        ///  v1.4-a T4：`Stage::load_inline` 已砍（D12）。本 FFI 暂保留（T7 决定是否砍/改），
        ///  内部直接调 parse_html + resolve_styles + build_scene（同旧 load_inline 逻辑）。
        ///  textures/atlases 已砍，不涉及纹理注册。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_load_html", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_load_html(StageHandle* h, byte* html, nuint html_len, byte* css, nuint css_len);

        /// <summary>
        ///  装载二进制包（spec §12/§13）。name = 包名（进 packages 字典 key），bytes = .pkg.bin。
        ///  0=ok，-1=err。null 句柄/空指针返回 -1。包是 Rust-internal，C# 只透传 bytes（不解析）。
        ///
        ///  **常驻（不 gate）：**包格式是 runtime 的稳定入口，不依赖 parse feature——
        ///  `--no-default-features` 构建的 .dll 仍有本函数（Unity 用 default 带 parse 的 dev .dll）。
        ///
        ///  v1.4-a T7：FFI 签名加 name 参数（对齐 T4 `Stage::load_package(name, bytes)`）。
        ///  load_package 只进资源池不建 scene——Unity 侧需先 create_root 建 scene 再 instantiate 建内容。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_load_package", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_load_package(StageHandle* h, byte* name, nuint name_len, byte* bytes, nuint bytes_len);

        /// <summary>
        ///  从包克隆一个组件进当前 scene，返组件根 NodeId（u32）。
        ///  pkg/comp = UTF-8 字节（指针+len）。失败返 0xFFFF_FFFF（INVALID，同 create_root 失败语义）。
        ///  scene 必须已存在（create_root 先建），否则 Err→sentinel。null 句柄 → sentinel。
        ///
        ///  **常驻（不 gate）。**v1.4-a T7：包装 T5 `Stage::instantiate(pkg, comp)`（spec §4.2/§4.4）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_instantiate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint loomgui_stage_instantiate(StageHandle* h, byte* pkg, nuint pkg_len, byte* comp, nuint comp_len);

        /// <summary>
        ///  跑一帧 tick_and_render → build_blob 写入缓存。dt 累积进 time_s（双击窗口，C# 传 unscaledDeltaTime）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_tick", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_tick(StageHandle* h, float dt);

        /// <summary>
        ///  借出最近一帧 blob：写 len 到 out_len，返回 Rust 拥有缓存指针（下 tick 失效）。
        ///  null 句柄或未 tick 过返回 null + len=0。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_borrow_frame", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* loomgui_stage_borrow_frame(StageHandle* h, nuint* out_len);

        /// <summary>
        ///  dump 整树 JSON（调试）。返 Rust 拥有的 UTF-8 C 串 + len；下 tick 失效。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_dump_scene", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* loomgui_stage_dump_scene(StageHandle* h, nuint* out_len);

        /// <summary>
        ///  注入本帧指针事件（扁平 PointerEvent 数组）。tick 前调。
        ///  null/len=0 = 本帧无输入事件（清空 pending_input，hover diff 仍跑——指针位置沿用上帧 last_pos）。
        ///
        ///  **常驻（不 gate）：**输入是 runtime 稳定入口，`--no-default-features` 构建的 .dll 仍有本函数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_input", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_set_input(StageHandle* h, PointerEvent* events, nuint len);

        /// <summary>
        ///  拉取本帧事件 SOA（pull，同 borrow_frame 语义）。返 `last_events` 的 `as_ptr` + 写 len。
        ///  null 句柄或未 tick（last_events 空）→ null + len=0。指针下 tick 失效。
        ///
        ///  **常驻（不 gate）：**事件是 runtime 稳定入口。EventRecord 是 `#[repr(C)]` POD，
        ///  C 侧按 `len * sizeof(EventRecord)` 切片读。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_borrow_events", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* loomgui_stage_borrow_events(StageHandle* h, nuint* out_len);

        /// <summary>
        ///  UI 挡住时游戏不响应点击（§10.6）。= 任一活跃槽 last_hit 非空且非根（多指：鼠标 slot0 + 已分配触摸槽）。
        ///  null 句柄 → false。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_is_pointer_on_ui", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool loomgui_stage_is_pointer_on_ui(StageHandle* h);

        /// <summary>
        ///  业务设节点 disabled 状态（伪类源 + active/click 抑制）。NodeId.0 越界静默跳过。
        ///  null 句柄 → no-op。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_node_disabled", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_set_node_disabled(StageHandle* h, uint node_id, [MarshalAs(UnmanagedType.U1)] bool disabled);

        /// <summary>
        ///  返 parent node_id（C# 事件路由沿链用，spec §4.2）。根/越界/无 scene → 0xFFFF_FFFF（sentinel）。
        ///
        ///  **常驻（不 gate）：**runtime 稳定入口，`--no-default-features` 构建的 .dll 仍有本函数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_node_parent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint loomgui_node_parent(StageHandle* h, uint node_id);

        /// <summary>
        ///  按 CSS id 属性查节点（业务用 id 定位节点替代硬编码 build 序 id）。
        ///  id = UTF-8 字节（指针+len）。返 node_id；null 句柄/非 UTF-8/无匹配 → 0xFFFF_FFFF（sentinel，同 node_parent）。
        ///
        ///  **常驻（不 gate）：**runtime 稳定入口，`--no-default-features` 构建的 .dll 仍有本函数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_find_node_by_id", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint loomgui_stage_find_node_by_id(StageHandle* h, byte* id, nuint id_len);

        /// <summary>
        ///  加 touch monitor（C# CaptureTouch 后调）。核心把 node 加进 touch_id 对应槽的 touch_monitors（去重）。
        ///  touch_id=-1 → 鼠标主指槽；找不到槽 → no-op。null 句柄 → no-op。
        ///
        ///  **常驻（不 gate）：**runtime 稳定入口。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_add_touch_monitor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_add_touch_monitor(StageHandle* h, int touch_id, uint node_id);

        /// <summary>
        ///  移除 touch monitor（C# 主动释放调）。从所有槽移除该 node。null 句柄 → no-op。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_remove_touch_monitor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_remove_touch_monitor(StageHandle* h, uint node_id);

        /// <summary>
        ///  外部取消待 click（照 fgui Stage.CancelClick(touchId)）。置对应槽 click_cancelled。
        ///  null 句柄 → no-op。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_cancel_click", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_cancel_click(StageHandle* h, int touch_id);

        /// <summary>
        ///  注入本帧键盘事件（扁平 KeyEvent 数组）。tick 前调。null/len=0 = 无键盘输入。
        ///
        ///  **常驻（不 gate）：**输入是 runtime 稳定入口。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_key_input", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_set_key_input(StageHandle* h, KeyEvent* keys, nuint len);

        /// <summary>
        ///  注入本帧滚轮事件（扁平 WheelEvent 数组）。tick 前调；**累积式**（多次调合并）。
        ///  null/len=0 = 本帧无滚轮（直接 return，不清空——与 set_key_input 不同；累积语义）。
        ///
        ///  **常驻（不 gate）：**输入是 runtime 稳定入口。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_wheel_input", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_set_wheel_input(StageHandle* h, WheelEvent* events, nuint len);

        /// <summary>
        ///  编程滚动到指定位置。非 scroll 容器 / 越界 node → no-op（不 panic）。
        ///  animated: u8（0=瞬移 1=缓动 cubic-out）。null 句柄 → no-op。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_scroll_pos", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_set_scroll_pos(StageHandle* h, uint node_id, float x, float y, byte animated);

        /// <summary>
        ///  v1.4-b：driver 注入滚动容器 content_size（虚拟列表）。node 无效/非滚动容器 → no-op。
        ///  null 句柄 → no-op（不 panic）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_content_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_set_content_size(StageHandle* h, uint node_id, float w, float height);

        /// <summary>
        ///  v1.4-b：清除 driver 注入的 content_size override（列表销毁/退回普通滚动时用）。
        ///  null 句柄/无效 node → no-op（不 panic）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_clear_content_size_override", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_clear_content_size_override(StageHandle* h, uint node_id);

        /// <summary>
        ///  v1.4-b：读 scroll_pos。null 句柄/无效 node → out 填 0（不 panic）。
        ///  out_x/out_y 是 out 参数（C# 传 ref float）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_get_scroll_pos", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_get_scroll_pos(StageHandle* h, uint node_id, float* out_x, float* out_y);

        /// <summary>
        ///  v1.4-b：读节点 layout_rect。null 句柄/无效 node → out 填 0（不 panic）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_get_node_layout_rect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_get_node_layout_rect(StageHandle* h, uint node_id, float* out_x, float* out_y, float* out_w, float* out_h);

        /// <summary>
        ///  v1.4-b：设渲染复用键（虚拟列表 slot）。null 句柄/无效 node → no-op。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_reuse_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_set_reuse_key(StageHandle* h, uint node_id, uint key);

        /// <summary>
        ///  编程聚焦节点（照 fgui RequestFocus）。强制聚焦任意非 disabled 节点
        ///  （含 tabindex=None/-1）；disabled 拒；越界跳过。null 句柄 → no-op。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_request_focus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_request_focus(StageHandle* h, uint node_id);

        /// <summary>
        ///  读当前焦点节点。无焦点/无 scene → 0xFFFF_FFFF（sentinel，同 node_parent）。null 句柄 → sentinel。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_focused_node", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint loomgui_stage_focused_node(StageHandle* h);

        /// <summary>
        ///  全局 shutdown（Domain reload hook）。C# `LoomStage.ResetStatics`（SubsystemRegistration）调用。
        ///
        ///  当前核心无全局 native 态——Stage 是 per-handle（`loomgui_stage_free` drop 全部 Stage 拥有的内存），
        ///  故本函数 near-no-op。但 hook 必须存在：将来引入全局 texture/font registry（进程级单例缓存）时，
        ///  此处自动成为清理入口，无需再改 C# 接线。
        ///
        ///  **注意：Font 的 `Box::leak`（`text/layout.rs:76`）是真泄漏**——`bytes.clone()` 后 leak 取
        ///  `'static` 切片喂 ttf-parser Face，原 Vec 虽被 `_bytes` 持有但与 leaked 切片不是同一份，
        ///  Stage drop 时 `_bytes` 释放的是 clone 来源而非 leaked 副本。每次 Stage 创建都 leak 一份字体字节，
        ///  不可由 shutdown 回收（leak 切片无 handle 跟踪）。若未来域重载内存观测触发阈值，
        ///  再考虑字体缓存化为进程单例。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_shutdown();

        /// <summary>
        ///  注册 tween。start/end 指向 ≥value_size 个 f32（value_size 由 prop 隐含）。
        ///  null 句柄/null 指针 → no-op。越界 node / duration&lt;=0 由 core update 处理（跳过/立即 complete）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_tween", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_tween(StageHandle* h, uint node_id, uint prop, float* start, float* end, float duration, uint ease, float delay, uint tag);

        /// <summary>
        ///  停该节点该 prop 的 tween（override 保留末值）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_kill_tween", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_kill_tween(StageHandle* h, uint node_id, uint prop);

        /// <summary>
        ///  清该节点所有动画 override（回 CSS）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_clear_anim", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_clear_anim(StageHandle* h, uint node_id);

        /// <summary>
        ///  清该节点某 prop 对应通道（回 CSS）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_clear_anim_prop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void loomgui_stage_clear_anim_prop(StageHandle* h, uint node_id, uint prop);

        /// <summary>
        ///  建根节点并设为 roots[0]。kind/css = UTF-8 字节。返 NodeId；0xFFFF_FFFF = 失败。
        ///
        ///  **常驻（不 gate）：**runtime 稳定入口，`--no-default-features` 构建的 .dll 仍有本函数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_create_root", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint loomgui_stage_create_root(StageHandle* h, byte* kind, nuint kind_len, byte* css, nuint css_len);

        /// <summary>
        ///  建节点（不挂父）。kind/css = UTF-8 字节。返 NodeId；0xFFFF_FFFF = 失败。
        ///  需配合 append_child/insert_before 挂到树。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_create_node", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint loomgui_stage_create_node(StageHandle* h, byte* kind, nuint kind_len, byte* css, nuint css_len);

        /// <summary>
        ///  挂子到 parent 末尾。child 必须当前无父。0=ok，-1=err。null 句柄 → -1。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_append_child", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_append_child(StageHandle* h, uint parent, uint child);

        /// <summary>
        ///  在 parent.children 中 ref_id 之前插 child。ref_id=0xFFFF_FFFF（INVALID）→ 末尾追加。
        ///  0=ok，-1=err。null 句柄 → -1。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_insert_before", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_insert_before(StageHandle* h, uint parent, uint child, uint ref_id);

        /// <summary>
        ///  摘子（不删节点）：从 parent.children 移除 + child.parent=None。节点仍 live 可重挂。
        ///  0=ok，-1=err。null 句柄 → -1。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_remove_child", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_remove_child(StageHandle* h, uint parent, uint child);

        /// <summary>
        ///  删节点（递归删子 + 联动清 anim/scroll/tween + slotmap remove）。
        ///  旧 NodeId 此后失效（gen++）。无 scene / 已删节点 → no-op。返 0（恒成功，no-op 语义）。
        ///  null 句柄 → 0（no-op，不 panic）。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_remove_node", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_remove_node(StageHandle* h, uint node);

        /// <summary>
        ///  改 Text 节点 content + 标 dirty_text。text = UTF-8 字节。0=ok，-1=err。
        ///  非 Text 节点 → -1（Stage::set_text Err）。null 句柄 → -1。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_set_text(StageHandle* h, uint node, byte* text, nuint len);

        /// <summary>
        ///  改 Image 节点 src + 标 dirty_mesh。src = UTF-8 字节。0=ok，-1=err。
        ///  非 Image 节点 → -1。null 句柄 → -1。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_src", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_set_src(StageHandle* h, uint node, byte* src, nuint len);

        /// <summary>
        ///  改 base_style（apply_css）+ 标 dirty_mesh。css = UTF-8 字节。0=ok，-1=err。
        ///  下帧 rematch 从 base 重算 style。null 句柄 → -1。
        ///
        ///  **常驻（不 gate）。**
        /// </summary>
        [DllImport(__DllName, EntryPoint = "loomgui_stage_set_style", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int loomgui_stage_set_style(StageHandle* h, uint node, byte* css, nuint len);


    }

    /// <summary>
    ///  opaque 句柄：Stage + 缓存的最近一帧 blob（borrow_frame 返回它的指针，下帧 reset）。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct StageHandle
    {
    }



}
